# Generated by Django 6.0.3 on 2026-03-25 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_profile_profile_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='suspended',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='suspended_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
