# Generated by Django 6.0.3 on 2026-03-26 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_auditlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='force_password_change',
            field=models.BooleanField(default=False),
        ),
    ]
