# Generated by Django 6.0.3 on 2026-03-26 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0006_profile_force_password_change'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='email_sent',
            field=models.BooleanField(default=False),
        ),
    ]
